version: '3.4'

services:
  zipapi:
    image: ${DOCKER_REGISTRY-}zipapi
    build:
      context: .
      dockerfile: ZipAPI/Dockerfile
    environment:
      DBServer: 'ms-sql-server'
    depends_on:
      - ms-sql-server
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ssword1'
    ports:
      - '1433:1433'